### PR TITLE
Add a DRS Client

### PR DESCRIPTION
**Pull request by pr80ik**

### CODE REVIEW

**Comment by jb-adams** [comment]
Hi Pratik, 

Nice work with the DRS component of the testbed. My client might have been hard to use for the testbed because it was written more as an end-to-end solution (ie. someone could execute it from the command line to download json and object bytes), so right now it doesn't really have the individual methods exposed.

I can update my DRS client to expose some more API methods, that might make it integrate better with the testbed. How does this sound? Can you let me know some of the testbed scenarios you've thought of? That way, I'll have a better idea of what API methods to expose.

**Comment by pr80ik** [comment]
@jb-adams The testbed would need to invoke each API endpoint and inspect the response to confirm that it is in spec.

So if there is a way to execute each DRS method with the ability to pass each supported parameter and get back the json payload and the http error codes that will be useful in the context of the testbed. As you can see the TRS example, it uses http client directly for this purpose.

If your _drs client_ has this functionality we should be able to completely remove 'ga4ghtest/services/drs/client.py'

**Comment by jb-adams** [comment]
I can add these methods to the drs client but they will take some time, I think it might be best to go ahead with your PR and maybe we can modify this testbed component later

**Comment by jaeddy** [comment]
Agreed with @jb-adams — this should be good to get us started, then we can add support for the more fleshed out client library after we figure out requirements.

**Review by jaeddy — APPROVED** [review]
Looks good — thanks @pr80ik!

**Pull request merged**
